<Project>
  <PropertyGroup>
    <Authors>KOZAKI Tsuneaki</Authors>
    <RepositoryUrl>https://github.com/koko-u/KozLibraries</RepositoryUrl>
    <MinVerTagPrefix>v</MinVerTagPrefix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
