<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Dapper" Version="2.1.79" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Npgsql.DependencyInjection" Version="10.0.3" />
  </ItemGroup>
</Project>
