<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
      
      <PackageId>kozLibraries.AutoRegisterAnnotation</PackageId>
      <Version>0.1.0</Version>
      <Authors>KOZAKI Tsuneaki</Authors>
      <Description>My Personal .NET Common Library for Services</Description>
      <RepositoryUrl>https://github.com/koko-u/KozLibraries</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference
      Include="Microsoft.Extensions.DependencyInjection.Abstractions"
      Version="10.0.7"
    />
  </ItemGroup>
</Project>
