<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>KozLibraries.TransactionRunner</PackageId>
    <Description>My Personal .NET Common Library for Npgsql Transaction</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.DependencyInjection" />
  </ItemGroup>
</Project>
